### PR TITLE
parse url encoded body

### PR DESCRIPTION
**Pull request by zhaotian2470**

### CODE REVIEW

**Comment by Will2817** [comment]
@pracucci any chance this could be merged?

**Comment by pracucci** [comment]
Thanks @zhaotian2470 for submitting this PR and sorry for the very late reply (I somewhat lost the notification). Do you mind give me more details about the expected behaviour after your change and if - in your opinion - it may break the current behaviour and thus being considered a breaking change?

**Comment by zhaotian2470** [comment]
@pracucci The PR is used to parse urlencoded bodies, then we can access it in filter function.  I think it is not a breaking change. Please refer to [bodyParser.urlencoded([options])](https://github.com/expressjs/body-parser#bodyparserurlencodedoptions)

Let us take an example. 
If we setup server like this:

```javascript
server.on({
    method: 'POST',
    path: '/',
    filter: function(req) {
	console.log(req.body);
	return true;
    },
    reply: {
	status:  200,
	headers: { "content-type": "application/json" },
	body:    JSON.stringify({ hello: "world" })
    }
});
```

Then execute command in another terminal: `curl -X POST --data-urlencode "a=1" http://<ip>:<port>`
Current filter will output req.body as "undefined".
After change, program will parse body and ouput  "{ a: '1' }"

**Comment by yizhiheng** [comment]
@pracucci Any news?

**Comment by pracucci** [comment]
Released version [`1.1.0`](https://github.com/spreaker/node-mock-http-server/releases/tag/1.1.0). Thanks for your patience!

**Pull request merged**
