### PR TITLE
Fix timeouts for multipart/form-data

### LINKED ISSUE #33: v1.4.3+ results in ESOCKETTIMEDOUT error
I've recently upgraded a project using v1.4.2 to v.1.4.4 and found that tests I'm using the mock server in are failing with `ESOCKETTIMEDOUT` errors. If I roll back to 1.4.2 the issue goes away.

It appears that the body-parser.text() function on line 203 of server.js is causing a problem, if this is commented out then the tests pass as expected.

edit: The content type is `multipart/form-data`

### PR DESCRIPTION
**Pull request by dhensby**
fixes #33

### CODE REVIEW

**Review by 0xvbetsun — APPROVED** [review]

**Comment by dhensby** [comment]
@teorossi82 @lele85 is it possible to have some eyes on this issue? The multi-part implementation is basically broken as of 1.4.3 and it would be nice to get a working version released.

**Comment by dhensby** [comment]
@teorossi82 @lele85 any chance you can look at this?

**Comment by teorossi82** [comment]
@dhensby thanks! We are going to check it during this week.

/cc @lele85

**Comment by dhensby** [comment]
Bump @teorossi82 @lele85 👼

**Review by lele85 — APPROVED** [review]

**Comment by lele85** [comment]
@dhensby Done!

**Pull request merged**
