### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by rickdgeerling**
Addresses #28

### CODE REVIEW

**Comment by iliasmentz** [comment]
Hey, any chance for this to get merged?

**Review by iliasmentz — APPROVED** [review]

**Comment by rickdgeerling** [comment]
In the mean time, you can add the `index.d.ts` file in your own repo under `types/mock-http-server`

**Review by 0xvbetsun — APPROVED** [review]

**Comment by pietro909** [comment]
I suggest pushing them to [Definitely Typed](https://www.typescriptlang.org/dt/search?search=) in the meanwhile. It is also suggested in _Effective Typescript_ to keep them separated so that we don't need to wait for the maintainers of a non-TS repo to act on type-related issues.

**Comment by rickdgeerling** [comment]
@pietro909 Please be my guest if you've got the time. I'm short on time and I'm no longer using this library so there's little incentive for me to continue working on this.

**Comment by pietro909** [comment]
Sorry @tuxmachine saw now: I've found it faster to migrate to https://github.com/httptoolkit/mockttp which exposes a very similar interface and is written in TS.

**Pull request closed without merging**
